<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>unlp.oo1</groupId>
		<artifactId>parent</artifactId>
		<relativePath>../../pom.xml</relativePath>
		<version>1.0.0</version>
	</parent>
	<artifactId>ej5-genealogia_salvaje</artifactId>
	<packaging>jar</packaging>
	<description>Ejercicio 5 Genealogia Salvaje</description>

	<dependencies>
		<dependency>
			<groupId>unlp.oo1</groupId>
			<artifactId>ej5-genealogia-salvaje-impl</artifactId>
			<version>1.0.0</version>
		</dependency>
	</dependencies>
</project>
